// <auto-generated />
using System;
using Coacher.Lib.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coacher.Lib.DAL.Migrations
{
    [DbContext(typeof(CoacherDbContext))]
    partial class CoacherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.ClosedListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "DisplayOrder");

                    b.ToTable("ClosedListItems");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("DefaultTimeBeforeExerciseToStartTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SeriesId");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplateDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DependsOnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnId");

                    b.HasIndex("TemplateId", "DependsOnId")
                        .IsUnique()
                        .HasFilter("[TemplateId] IS NOT NULL AND [DependsOnId] IS NOT NULL");

                    b.ToTable("TaskTemplateDependencies");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplateInfluencer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("InfluencerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InfluencerId");

                    b.HasIndex("TemplateId", "InfluencerId")
                        .IsUnique()
                        .HasFilter("[TemplateId] IS NOT NULL AND [InfluencerId] IS NOT NULL");

                    b.ToTable("TaskTemplateInfluencers");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EchelonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EchelonId");

                    b.HasIndex("Name");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchiveTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArchivedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CompressionFactor")
                        .HasColumnType("float");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TraineeUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrainerUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EndDate");

                    b.HasIndex("StartDate");

                    b.HasIndex("StatusId");

                    b.HasIndex("TraineeUnitId");

                    b.HasIndex("TrainerUnitId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseInfluencer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InfluencerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InfluencerId");

                    b.HasIndex("ExerciseId", "InfluencerId")
                        .IsUnique()
                        .HasFilter("[ExerciseId] IS NOT NULL AND [InfluencerId] IS NOT NULL");

                    b.ToTable("ExerciseInfluencers");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId");

                    b.ToTable("ExerciseParticipants");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("ExerciseId", "SectionId")
                        .IsUnique()
                        .HasFilter("[ExerciseId] IS NOT NULL AND [SectionId] IS NOT NULL");

                    b.ToTable("ExerciseSections");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseUnitContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseId", "ContactType");

                    b.ToTable("ExerciseUnitContacts");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.ExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalIdValue")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid?>("ExternalSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExternalIdValue");

                    b.HasIndex("ExternalSourceId");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalIds");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Notifications.UserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId", "CreationTime");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasChildren")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStatusUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastStatusUpdaterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SourceId");

                    b.HasIndex("StatusId");

                    b.ToTable("ExerciseTasks");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.ExerciseTaskResponsibleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TaskId", "UserId")
                        .IsUnique()
                        .HasFilter("[TaskId] IS NOT NULL AND [UserId] IS NOT NULL");

                    b.ToTable("ExerciseTaskResponsibleUsers");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DependsOnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnId");

                    b.HasIndex("TaskId", "DependsOnId")
                        .IsUnique()
                        .HasFilter("[TaskId] IS NOT NULL AND [DependsOnId] IS NOT NULL");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CivilianEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MilitaryEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PersonalNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Position")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Rank")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdentityNumber")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplate", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.TaskTemplate", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Parent");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplateDependency", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.TaskTemplate", "DependsOn")
                        .WithMany("DependedOnBy")
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.TaskTemplate", "Template")
                        .WithMany("Dependencies")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DependsOn");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplateInfluencer", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Influencer")
                        .WithMany()
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.TaskTemplate", "Template")
                        .WithMany("Influencers")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Influencer");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.Unit", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Echelon")
                        .WithMany()
                        .HasForeignKey("EchelonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Echelon");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.Exercise", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Users.UserProfile", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.Unit", "TraineeUnit")
                        .WithMany()
                        .HasForeignKey("TraineeUnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.Unit", "TrainerUnit")
                        .WithMany()
                        .HasForeignKey("TrainerUnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Status");

                    b.Navigation("TraineeUnit");

                    b.Navigation("TrainerUnit");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseInfluencer", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Exercises.Exercise", "Exercise")
                        .WithMany("Influencers")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Influencer")
                        .WithMany()
                        .HasForeignKey("InfluencerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exercise");

                    b.Navigation("Influencer");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseParticipant", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Exercises.Exercise", "Exercise")
                        .WithMany("Participants")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Users.UserProfile", "User")
                        .WithMany("ExerciseParticipants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseSection", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Exercises.Exercise", "Exercise")
                        .WithMany("Sections")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exercise");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.ExerciseUnitContact", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Exercises.Exercise", "Exercise")
                        .WithMany("UnitContacts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.ExternalId", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "ExternalSource")
                        .WithMany()
                        .HasForeignKey("ExternalSourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Users.UserProfile", "User")
                        .WithMany("ExternalIds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExternalSource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Notifications.UserNotification", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Exercises.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Users.UserProfile", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Coacher.Shared.Models.DAL.Exercises.Exercise", "Exercise")
                        .WithMany("Tasks")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.TaskTemplate", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Admin.ClosedListItem", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Exercise");

                    b.Navigation("Parent");

                    b.Navigation("Series");

                    b.Navigation("Source");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.ExerciseTaskResponsibleUser", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", "Task")
                        .WithMany("ResponsibleUsers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Users.UserProfile", "User")
                        .WithMany("ResponsibleTaskLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.TaskDependency", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", "DependsOn")
                        .WithMany("DependedOnBy")
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", "Task")
                        .WithMany("Dependencies")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DependsOn");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.UserProfile", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Admin.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.UserRole", b =>
                {
                    b.HasOne("Coacher.Shared.Models.DAL.Users.UserProfile", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Admin.TaskTemplate", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DependedOnBy");

                    b.Navigation("Dependencies");

                    b.Navigation("Influencers");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Exercises.Exercise", b =>
                {
                    b.Navigation("Influencers");

                    b.Navigation("Participants");

                    b.Navigation("Sections");

                    b.Navigation("Tasks");

                    b.Navigation("UnitContacts");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Tasks.ExerciseTask", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("DependedOnBy");

                    b.Navigation("Dependencies");

                    b.Navigation("ResponsibleUsers");
                });

            modelBuilder.Entity("Coacher.Shared.Models.DAL.Users.UserProfile", b =>
                {
                    b.Navigation("ExternalIds");

                    b.Navigation("ExerciseParticipants");

                    b.Navigation("Notifications");

                    b.Navigation("ResponsibleTaskLinks");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
